# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2025-04-19 13:58:24
"""
import arcpy
from arcpy.ia import *
from arcpy.ia import *
from arcpy.sa import *
from arcpy.sa import *
from arcpy.sa import *

def OATCRugosity():  # OATCRugosity

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    # Check out any necessary licenses.
    arcpy.CheckOutExtension("spatial")
    arcpy.CheckOutExtension("ImageAnalyst")
    arcpy.CheckOutExtension("3D")

    OATC_Elevation_P_M = arcpy.Raster("Admin\\OATC_Elevation_P_M")

    # Process: Aspect (Aspect) (sa)
    OATC_Aspect = "F:\\Grad\\Thesis\\Thesis_Working\\Thesis_Working.gdb\\OATC_Aspect"
    Aspect = OATC_Aspect
    OATC_Aspect = arcpy.sa.Aspect(OATC_Elevation_P_M, "PLANAR", "METER", "GEODESIC_AZIMUTHS", "GPU_THEN_CPU")
    OATC_Aspect.save(Aspect)


    # Process: Slope (Slope) (sa)
    OATC_Slope = "F:\\Grad\\Thesis\\Thesis_Working\\Thesis_Working.gdb\\OATC_Slope"
    Slope = OATC_Slope
    OATC_Slope = arcpy.sa.Slope(OATC_Elevation_P_M, "DEGREE", 1, "PLANAR", "METER", "GPU_THEN_CPU")
    OATC_Slope.save(Slope)


    # Process: Focal Statistics (Focal Statistics) (ia)
    OATC_3x3SD = "F:\\Grad\\Thesis\\Thesis_Working\\Thesis_Working.gdb\\OATC_3x3SD"
    Focal_Statistics = OATC_3x3SD
    with arcpy.EnvManager(cellSize="MAXOF", mask="ModelBuilder\\OATC_TreadSmoothed:OATC_TreadSmoothed"):
        OATC_3x3SD = arcpy.ia.FocalStatistics(OATC_Elevation_P_M, "Rectangle 0.5 0.5 MAP", "STD", "DATA", 90)
        OATC_3x3SD.save(Focal_Statistics)


    # Process: Times (2) (Times) (ia)
    OATC_Rugosity = "F:\\Grad\\Thesis\\Thesis_Working\\Thesis_Working.gdb\\OATC_Rugosity"
    Times_2_ = OATC_Rugosity
    with arcpy.EnvManager(mask="ModelBuilder\\OATC_TreadSmoothed:OATC_TreadSmoothed", snapRaster="OATC_Width:OATC_Width"):
        OATC_Rugosity = arcpy.ia.Times(OATC_3x3SD, OATC_3x3SD)
        OATC_Rugosity.save(Times_2_)


    # Process: Reclassify (3) (Reclassify) (sa)
    OATC_Rugosity_John_Reclass = "F:\\Grad\\Thesis\\Thesis_Working\\Thesis_Working.gdb\\OATC_Rugosity_John_Reclass"
    Reclassify_3_ = OATC_Rugosity_John_Reclass
    OATC_Rugosity_John_Reclass = arcpy.sa.Reclassify(OATC_Rugosity, "VALUE", "0.000024 0.000142 1;0.000142 0.017821 2;0.017821 0.035500 3;0.035500 0.053179 4;0.053179 0.325686 5", "DATA")
    OATC_Rugosity_John_Reclass.save(Reclassify_3_)


if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(scratchWorkspace="F:\\Grad\\Thesis\\Thesis_Working\\Thesis_Working.gdb", workspace="F:\\Grad\\Thesis\\Thesis_Working\\Thesis_Working.gdb"):
        OATCRugosity()
