# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2025-04-19 13:58:40
"""
import arcpy
from arcpy.ia import *
from arcpy.sa import *
from arcpy.sa import *

def OATCIncision():  # OATCIncision

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    # Check out any necessary licenses.
    arcpy.CheckOutExtension("spatial")
    arcpy.CheckOutExtension("ImageAnalyst")
    arcpy.CheckOutExtension("3D")

    OATC_Imagery_tif = arcpy.Raster("Admin\\OATC_Imagery_P")
    OATC_StudyArea = "OATC_StudyArea"
    OATC = "F:\\Grad\\Thesis\\Thesis_Working\\Thesis_Working.gdb\\OATC"
    OATC_TrailTread = "OATC_TreadSmoothed:OATC_TreadSmoothed"
    OATCTrail_ElevationToolbox_export_TueAug06141801491880_tif = arcpy.Raster("Admin\\OATC_Elevation_P_M")

    # Process: Clip Raster (Clip Raster) (management)
    OATC_OrthoClip = "F:\\Grad\\Thesis\\Thesis_Working\\Thesis_Working.gdb\\OATC_OrthoClip"
    arcpy.management.Clip(in_raster=OATC_Imagery_tif, rectangle="492658.4116 4039215.2936 492754.1533 4039298.1818", out_raster=OATC_OrthoClip, in_template_dataset=OATC_StudyArea, clipping_geometry="ClippingGeometry")
    OATC_OrthoClip = arcpy.Raster(OATC_OrthoClip)

    # Process: Export Features (Export Features) (conversion)
    OATC_UnmoddedTerrain = "F:\\Grad\\Thesis\\Thesis_Working\\Thesis_Working.gdb\\OATC_UnmoddedTerrain"
    arcpy.conversion.ExportFeatures(in_features=OATC_StudyArea, out_features=OATC_UnmoddedTerrain, field_mapping="BUFF_DIST \"BUFF_DIST\" true true false 8 Double 0 0,First,#,F:\\Grad\\Thesis\\Thesis_Working\\Thesis_Working.gdb\\OATC_StudyArea,BUFF_DIST,-1,-1;ORIG_FID \"ORIG_FID\" true true false 4 Long 0 0,First,#,F:\\Grad\\Thesis\\Thesis_Working\\Thesis_Working.gdb\\OATC_StudyArea,ORIG_FID,-1,-1;Shape_Length \"Shape_Length\" false true true 8 Double 0 0,First,#,F:\\Grad\\Thesis\\Thesis_Working\\Thesis_Working.gdb\\OATC_StudyArea,Shape_Length,-1,-1;Shape_Area \"Shape_Area\" false true true 8 Double 0 0,First,#,F:\\Grad\\Thesis\\Thesis_Working\\Thesis_Working.gdb\\OATC_StudyArea,Shape_Area,-1,-1")

    # Process: Erase (Erase) (analysis)
    OATC_UnmoddedTerrain_Erase = "F:\\Grad\\Thesis\\Thesis_Working\\Thesis_Working.gdb\\OATC\\OATC_UnmoddedTerrain_Erase"
    arcpy.analysis.Erase(in_features=OATC_UnmoddedTerrain, erase_features=OATC_TrailTread, out_feature_class=OATC_UnmoddedTerrain_Erase)

    # Process: Create Random Points (Create Random Points) (management)
    OATC_RandomPoints = arcpy.management.CreateRandomPoints(out_path=OATC, out_name="OATC_RandomPoints", constraining_feature_class=OATC_UnmoddedTerrain_Erase, constraining_extent=OATC_UnmoddedTerrain_Erase, number_of_points_or_field=10000)[0]

    # Process: Clip Raster (2) (Clip Raster) (management)
    OATC_ElevClip = "F:\\Grad\\Thesis\\Thesis_Working\\Thesis_Working.gdb\\OATC_ElevClip"
    arcpy.management.Clip(in_raster=OATCTrail_ElevationToolbox_export_TueAug06141801491880_tif, rectangle="492658.4116 4039215.2936 492754.1533 4039298.1818", out_raster=OATC_ElevClip, in_template_dataset=OATC_StudyArea, clipping_geometry="ClippingGeometry")
    OATC_ElevClip = arcpy.Raster(OATC_ElevClip)

    # Process: Extract Values to Points (Extract Values to Points) (sa)
    OATC_UnmoddedPoints = "F:\\Grad\\Thesis\\Thesis_Working\\Thesis_Working.gdb\\OATC\\OATC_UnmoddedPoints"
    arcpy.sa.ExtractValuesToPoints(OATC_RandomPoints, OATC_ElevClip, OATC_UnmoddedPoints, "INTERPOLATE", "VALUE_ONLY")

    # Process: Kriging (Kriging) (sa)
    OATC_UnmoddedElevation = "F:\\Grad\\Thesis\\Thesis_Working\\Thesis_Working.gdb\\OATC_UnmoddedElevation"
    Kriging = OATC_UnmoddedElevation
    Output_variance_of_prediction_raster = ""
    with arcpy.EnvManager(mask="F:\\Grad\\Thesis\\Thesis_Working\\Thesis_Working.gdb\\OATC_StudyArea", snapRaster="OATC_Width:OATC_Width"):
        OATC_UnmoddedElevation = arcpy.sa.Kriging(OATC_UnmoddedPoints, "RASTERVALU", "Spherical 0.330794 # # #", "CIMPATH=oatc/oatc_elevation_p_m.json", "VARIABLE 12", Output_variance_of_prediction_raster)
        OATC_UnmoddedElevation.save(Kriging)


    # Process: Raster Calculator (Raster Calculator) (ia)
    OATC_Incision = "F:\\Grad\\Thesis\\Thesis_Working\\thesis_working.gdb\\OATC_Incision"
    Raster_Calculator = OATC_Incision
    with arcpy.EnvManager(mask="ModelBuilder\\OATC_TreadSmoothed:OATC_TreadSmoothed", snapRaster="OATC_Width:OATC_Width"):
        OATC_Incision = OATC_UnmoddedElevation - OATC_ElevClip
        OATC_Incision.save(Raster_Calculator)


    # Process: Reclassify (5) (Reclassify) (sa)
    OATC_Incision_John_Reclass = "F:\\Grad\\Thesis\\Thesis_Working\\Thesis_Working.gdb\\OATC_Incision_John_Reclass"
    Reclassify_5_ = OATC_Incision_John_Reclass
    with arcpy.EnvManager(snapRaster="OATC_Width:OATC_Width"):
        OATC_Incision_John_Reclass = arcpy.sa.Reclassify(OATC_Incision, "VALUE", "-1.047000 0 1;0 0.100000 2;0.100000 0.300000 3;0.300000 0.500000 4;0.500000 0.940000 5", "DATA")
        OATC_Incision_John_Reclass.save(Reclassify_5_)


if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(scratchWorkspace="F:\\Grad\\Thesis\\Thesis_Working\\Thesis_Working.gdb", workspace="F:\\Grad\\Thesis\\Thesis_Working\\Thesis_Working.gdb"):
        OATCIncision()
