# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2025-04-19 13:58:51
"""
import arcpy
from arcpy.sa import *
from sys import argv

def OATCWidth(OATC_TrailTread_Project="OATC_TrailTread"):  # OATCWidth

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    # Check out any necessary licenses.
    arcpy.CheckOutExtension("Foundation")
    arcpy.CheckOutExtension("Defense")
    arcpy.CheckOutExtension("3D")
    arcpy.CheckOutExtension("spatial")

    arcpy.ImportToolbox(r"c:\program files\arcgis\pro\Resources\ArcToolbox\toolboxes\Data Management Tools.tbx")
    OATC_TrailTread = "OATC_TrailTread"
    OATC_Width_OATC_Width = arcpy.Raster("OATC_Width:OATC_Width")

    # Process: Smooth Polygon (Smooth Polygon) (cartography)
    OATC_TreadSmoothed = "F:\\Grad\\Thesis\\Thesis_Working\\Thesis_Working.gdb\\OATC\\OATC_TreadSmoothed"
    with arcpy.EnvManager(transferGDBAttributeProperties=False):
        arcpy.cartography.SmoothPolygon(in_features=OATC_TrailTread_Project.__str__().format(**locals(),**globals()), out_feature_class=OATC_TreadSmoothed, algorithm="PAEK", tolerance="0.5 Meters")

    # Process: Polygon To Centerline (Polygon To Centerline) (topographic)
    OATC_TreadCenterline = "F:\\Grad\\Thesis\\Thesis_Working\\Thesis_Working.gdb\\OATC\\OATC_TreadCenterline"
    arcpy.topographic.PolygonToCenterline(in_features=OATC_TreadSmoothed, out_feature_class=OATC_TreadCenterline)

    # Process: Generate Transects Along Lines (Generate Transects Along Lines) (management)
    OATC_TreadTransects = "F:\\Grad\\Thesis\\Thesis_Working\\Thesis_Working.gdb\\OATC\\OATC_TreadTransects"
    arcpy.management.GenerateTransectsAlongLines(in_features=OATC_TreadCenterline, out_feature_class=OATC_TreadTransects, interval="0.5 Meters", transect_length="4 Meters", include_ends="END_POINTS")

    # Process: Clip (Clip) (analysis)
    OATC_TransectsClip = "F:\\Grad\\Thesis\\Thesis_Working\\Thesis_Working.gdb\\OATC\\OATC_TransectsClip"
    arcpy.analysis.Clip(in_features=OATC_TreadTransects, clip_features=OATC_TreadSmoothed, out_feature_class=OATC_TransectsClip)

    # Process: Add Field (Add Field) (management)
    NA_TransectsClip_3_ = arcpy.management.AddField(in_table=OATC_TransectsClip, field_name="Trail_Width", field_type="FLOAT")[0]

    # Process: Calculate Field (Calculate Field) (management)
    NA_TransectsClip_2_ = arcpy.management.CalculateField(in_table=NA_TransectsClip_3_, field="Trail_Width", expression="!Shape_Length!")[0]

    # Process: Buffer (Buffer) (analysis)
    OATC_TransectBuffer = "F:\\Grad\\Thesis\\Thesis_Working\\Thesis_Working.gdb\\OATC\\OATC_TransectBuffer"
    arcpy.analysis.Buffer(in_features=NA_TransectsClip_2_, out_feature_class=OATC_TransectBuffer, buffer_distance_or_field="0.5 Meters", line_side="FULL", line_end_type="ROUND", dissolve_option="NONE", method="PLANAR")

    # Process: Polygon to Raster (Polygon to Raster) (conversion)
    OATC_TransectsRaster = "F:\\Grad\\Thesis\\Thesis_Working\\Thesis_Working.gdb\\OATC_TransectsRaster"
    with arcpy.EnvManager(snapRaster="F:\\Grad\\Thesis\\Thesis_Working\\Thesis_Working.gdb\\OATC_Elevation_P_M"):
        arcpy.conversion.PolygonToRaster(in_features=OATC_TransectBuffer, value_field="Trail_Width", out_rasterdataset=OATC_TransectsRaster, cell_assignment="CELL_CENTER", priority_field="NONE", cellsize="CIMPATH=oatc/oatc_elevation_p_m.json", build_rat="BUILD")

    # Process: Raster to Point (Raster to Point) (conversion)
    OATC_Width_Points = "F:\\Grad\\Thesis\\Thesis_Working\\Thesis_Working.gdb\\OATC\\OATC_Width_Points"
    with arcpy.EnvManager(outputMFlag="Disabled", outputZFlag="Disabled"):
        arcpy.conversion.RasterToPoint(in_raster=OATC_TransectsRaster, out_point_features=OATC_Width_Points, raster_field="VALUE")

    # Process: Kriging (2) (Kriging) (3d)
    OATC_Width = "F:\\Grad\\Thesis\\Thesis_Working\\Thesis_Working.gdb\\OATC_Width"
    OATC_Width_Variance = "F:\\Grad\\Thesis\\Thesis_Working\\Thesis_Working.gdb\\OATC_Width_Variance"
    with arcpy.EnvManager(cellSize="MAXOF", mask="ModelBuilder\\OATC_TreadSmoothed:OATC_TreadSmoothed", snapRaster="Admin\\OATC_Elevation_P_M"):
        arcpy.ddd.Kriging(in_point_features=OATC_Width_Points, z_field="grid_code", out_surface_raster=OATC_Width, semiVariogram_props="Spherical 0.262550 # # #", cell_size="CIMPATH=oatc/oatc_elevation_p_m.json", out_variance_prediction_raster=OATC_Width_Variance)
        OATC_Width = arcpy.Raster(OATC_Width)
        OATC_Width_Variance = arcpy.Raster(OATC_Width_Variance)

    # Process: Reclassify (4) (Reclassify) (sa)
    OATC_Width_Reclass = "F:\\Grad\\Thesis\\Thesis_Working\\Thesis_Working.gdb\\OATC_Width_Reclass"
    Reclassify_4_ = OATC_Width_Reclass
    OATC_Width_Reclass = arcpy.sa.Reclassify(OATC_Width_OATC_Width, "VALUE", "0 0.500000 1;0.500000 1 2;1 1.500000 3;1.500000 1.750000 4;1.750000 3.361225 5", "DATA")
    OATC_Width_Reclass.save(Reclassify_4_)


if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(scratchWorkspace="F:\\Grad\\Thesis\\Thesis_Working\\Thesis_Working.gdb", workspace="F:\\Grad\\Thesis\\Thesis_Working\\Thesis_Working.gdb"):
        OATCWidth(*argv[1:])
