# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2025-04-19 13:55:55
"""
import arcpy
from arcpy.sa import *

def NATDM():  # NATDM

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    # Check out any necessary licenses.
    arcpy.CheckOutExtension("spatial")

    Rugosity_Reclass = arcpy.Raster("ModelBuilder\\NA_Rugosity_John_Reclass:NA_Rugosity_John_Reclass")
    Grade_Reclass = arcpy.Raster("ModelBuilder\\NA_Grade_John_Reclass:NA_Grade_John_Reclass")
    Incision_Reclass = arcpy.Raster("ModelBuilder\\NA_Incision_John_Reclass:NA_Incision_John_Reclass")
    Width_Reclass = arcpy.Raster("ModelBuilder\\NA_Width_John_Reclass (3):NA_Width_John_Reclass")

    # Process: Weighted Overlay (Weighted Overlay) (sa)
    Trail_Degradation_Model = "F:\\Grad\\Thesis\\Thesis_Working\\Thesis_Working.gdb\\NA_Weighted_Model_John_Custom"
    Weighted_Overlay = Trail_Degradation_Model
    Trail_Degradation_Model = arcpy.sa.WeightedOverlay(WOTable([[Rugosity_Reclass, 10 , 'Value' , RemapValue([[1, 1], [2, 2], [3, 3], [4, 4], [5, 5], ['NODATA', 'NODATA']])], [Grade_Reclass, 20 , 'Value' , RemapValue([[1, 1], [2, 2], [3, 3], [4, 4], [5, 5], ['NODATA', 'NODATA']])], [Incision_Reclass, 35 , 'Value' , RemapValue([[1, 1], [2, 2], [3, 3], [4, 4], [5, 5], ['NODATA', 'NODATA']])], [Width_Reclass, 35 , 'Value' , RemapValue([[1, 1], [2, 2], [3, 3], [4, 4], [5, 5], ['NODATA', 'NODATA']])]], [1, 9, 1]))
    Trail_Degradation_Model.save(Weighted_Overlay)


if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(scratchWorkspace="F:\\Grad\\Thesis\\Thesis_Working\\Thesis_Working.gdb", workspace="F:\\Grad\\Thesis\\Thesis_Working\\Thesis_Working.gdb"):
        NATDM()
