# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2025-04-19 13:57:00
"""
import arcpy
from arcpy.ia import *
from arcpy.ia import *
from arcpy.sa import *
from arcpy.sa import *
from arcpy.sa import *
from arcpy.sa import *

def TRRugosity():  # TRRugosity

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    # Check out any necessary licenses.
    arcpy.CheckOutExtension("3D")
    arcpy.CheckOutExtension("spatial")
    arcpy.CheckOutExtension("ImageAnalyst")

    ToothRidgeTrail_ElevationToolbox_export_SatAug10153610933470_tif = arcpy.Raster("Admin\\TR_Elevation_P_M1")
    TR_Rugosity_2_TR_Rugosity = arcpy.Raster("ModelBuilder\\Rugosity\\TR_Rugosity (2):TR_Rugosity")

    # Process: Aspect (Aspect) (sa)
    TR_Aspect = "F:\\Grad\\Thesis\\Thesis_Working\\Thesis_Working.gdb\\TR_Aspect"
    Aspect = TR_Aspect
    TR_Aspect = arcpy.sa.Aspect(ToothRidgeTrail_ElevationToolbox_export_SatAug10153610933470_tif, "PLANAR", "METER", "GEODESIC_AZIMUTHS", "GPU_THEN_CPU")
    TR_Aspect.save(Aspect)


    # Process: Slope (Slope) (sa)
    TR_Slope = "F:\\Grad\\Thesis\\Thesis_Working\\Thesis_Working.gdb\\TR_Slope"
    Slope = TR_Slope
    TR_Slope = arcpy.sa.Slope(ToothRidgeTrail_ElevationToolbox_export_SatAug10153610933470_tif, "DEGREE", 1, "PLANAR", "METER", "GPU_THEN_CPU")
    TR_Slope.save(Slope)


    # Process: Focal Statistics (2) (Focal Statistics) (ia)
    TR_3x3SD_2_ = "F:\\Grad\\Thesis\\Thesis_Working\\Thesis_Working.gdb\\TR_3x3SD"
    Focal_Statistics_2_ = TR_3x3SD_2_
    with arcpy.EnvManager(mask="ModelBuilder\\Width\\TR_TreadSmoothed:TR_TreadSmoothed", snapRaster="ModelBuilder\\Width\\TR_Width:TR_Width"):
        TR_3x3SD_2_ = arcpy.ia.FocalStatistics(ToothRidgeTrail_ElevationToolbox_export_SatAug10153610933470_tif, "Rectangle 0.5 0.5 MAP", "STD", "DATA", 90)
        TR_3x3SD_2_.save(Focal_Statistics_2_)


    # Process: Times (2) (Times) (ia)
    TR_Rugosity_2_ = "F:\\Grad\\Thesis\\Thesis_Working\\Thesis_Working.gdb\\TR_Rugosity"
    Times_2_ = TR_Rugosity_2_
    with arcpy.EnvManager(cellSize="ModelBuilder\\Width\\TR_Width:TR_Width", mask="ModelBuilder\\Width\\TR_TreadSmoothed:TR_TreadSmoothed", snapRaster="ModelBuilder\\Width\\TR_Width:TR_Width"):
        TR_Rugosity_2_ = arcpy.ia.Times(TR_3x3SD_2_, TR_3x3SD_2_)
        TR_Rugosity_2_.save(Times_2_)


    # Process: Reclassify (Reclassify) (sa)
    TR_Rugosity_Reclass = "F:\\Grad\\Thesis\\Thesis_Working\\Thesis_Working.gdb\\TR_Rugosity_Reclass"
    Reclassify = TR_Rugosity_Reclass
    with arcpy.EnvManager(snapRaster="ModelBuilder\\TR_Width:TR_Width"):
        TR_Rugosity_Reclass = arcpy.sa.Reclassify(TR_Rugosity_2_, "VALUE", "0 1;0 0.002058 2;0.002058 0.004115 3;0.004115 0.008231 4;0.008231 0.524709 5", "DATA")
        TR_Rugosity_Reclass.save(Reclassify)


    # Process: Reclassify (2) (Reclassify) (sa)
    TR_Rugosity_John_Reclass = "F:\\Grad\\Thesis\\Thesis_Working\\Thesis_Working.gdb\\TR_Rugosity_John_Reclass"
    Reclassify_2_ = TR_Rugosity_John_Reclass
    with arcpy.EnvManager(cellSize="ModelBuilder\\Width\\TR_Width:TR_Width", snapRaster="ModelBuilder\\Width\\TR_Width:TR_Width"):
        TR_Rugosity_John_Reclass = arcpy.sa.Reclassify(TR_Rugosity_2_TR_Rugosity, "VALUE", "0.000002 0.000512 1;0.000512 0.003603 2;0.003603 0.006694 3;0.006694 0.009786 4;0.009786 0.032805 5", "DATA")
        TR_Rugosity_John_Reclass.save(Reclassify_2_)


if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(scratchWorkspace="F:\\Grad\\Thesis\\Thesis_Working\\Thesis_Working.gdb", workspace="F:\\Grad\\Thesis\\Thesis_Working\\Thesis_Working.gdb"):
        TRRugosity()
