# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2025-04-19 13:58:06
"""
import arcpy
from arcpy.sa import *

def TRTDM():  # TRTDM

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    # Check out any necessary licenses.
    arcpy.CheckOutExtension("spatial")

    TR_Grade_Reclass_John = arcpy.Raster("F:\\Grad\\Thesis\\Thesis_Working\\Thesis_Working.gdb\\TR_Grade_Reclass_John")
    TR_Width_Reclass = arcpy.Raster("F:\\Grad\\Thesis\\Thesis_Working\\Thesis_Working.gdb\\TR_Width_Reclass")
    TR_Incision_Reclass = arcpy.Raster("F:\\Grad\\Thesis\\Thesis_Working\\Thesis_Working.gdb\\TR_Incision_Reclass")
    TR_Rugosity_John_Reclass = arcpy.Raster("F:\\Grad\\Thesis\\Thesis_Working\\Thesis_Working.gdb\\TR_Rugosity_John_Reclass")

    # Process: Weighted Overlay (4) (Weighted Overlay) (sa)
    TR_Weighted_Model_Custom_John_2_ = "F:\\Grad\\Thesis\\Thesis_Working\\Thesis_Working.gdb\\TR_Weighted_Model_Custom_John"
    Weighted_Overlay_4_ = TR_Weighted_Model_Custom_John_2_
    TR_Weighted_Model_Custom_John_2_ = arcpy.sa.WeightedOverlay(WOTable([[TR_Grade_Reclass_John, 20 , 'Value' , RemapValue([[1, 1], [2, 2], [3, 3], [4, 4], [5, 5], ['NODATA', 'NODATA']])], [TR_Width_Reclass, 35 , 'Value' , RemapValue([[0, 1], [2, 2], [3, 3], [4, 4], [5, 5], ['NODATA', 'NODATA']])], [TR_Incision_Reclass, 35 , 'Value' , RemapValue([[1, 1], [2, 2], [3, 3], [4, 4], [5, 5], ['NODATA', 'NODATA']])], [TR_Rugosity_John_Reclass, 10 , 'Value' , RemapValue([[1, 1], [2, 2], [3, 3], [4, 4], [5, 5], ['NODATA', 'NODATA']])]], [1, 9, 1]))
    TR_Weighted_Model_Custom_John_2_.save(Weighted_Overlay_4_)


if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(scratchWorkspace="F:\\Grad\\Thesis\\Thesis_Working\\Thesis_Working.gdb", workspace="F:\\Grad\\Thesis\\Thesis_Working\\Thesis_Working.gdb"):
        TRTDM()
